### ISSUE TITLE
using stream

### ISSUE THREAD

**Issue by chrisathook** [MikeKovarik/gulp-better-rollup#11]
I am trying to use this package downstream from some others in a gulp pipeline but when I do that none of the changes to the file make it to your module. Are you using the actual stream or are you loading the file again ?

In this example I can see that preprocess runs since I can see the modified file contents with intercept but then rollup is still using the original file not the modified version. 

    return gulp.src(options.src)
      .pipe(preprocess({context: require('../../compiler-directives')},{type: 'js'})).on('error', onError)
      .pipe(intercept(function (file) {
        console.log('FILE: ' + file.path);
        console.log('OLD CONTENT: ' + file.contents.toString());
      }))
      
      .pipe(sourcemaps.init())
      .pipe(rollup({
        plugins: [
          html({
            include: options.html, htmlMinifierOptions: {
              collapseWhitespace: true,
              collapseBooleanAttributes: true,
              conservativeCollapse: true,
              minifyJS: true
            }
          }),
          resolve({browser: true}),
          commonjs(),
          babel({
            exclude: ['node_modules/**', 'dist/**', 'vendor/**'],
            presets: ['es2015-rollup']
          }),
        ],
      }, {format: 'iife'})).on('error', onError)

**Comment by MikeKovarik** [comment]
The file is loaded again because that's how rollup works. This module is even blacklisted in gulp plugin list because of it. But this module was intentionally created with that in mind because there are other modules trying to mash gulp and rollup together, but they are subjected to ugly code, convoluted and not practical hacks so technically they might be using streams but honestly they suck.
