### ISSUE TITLE
Avoid auto assigning of `moduleId`

### ISSUE THREAD

**Issue by DevVersion** [MikeKovarik/gulp-better-rollup#3]
Hello, at first thanks for the good gulp plugin!

I'm planning to use the `gulp-better-rollup` plugin in  one of our projects to build UMD bundles.

In our `.umd` bundles we don't want to force the developers to a specific `moduleId` so we want to keep that option clear.

As per [this line](https://github.com/MikeKovarik/gulp-better-rollup/blob/master/index.js#L84) the `moduleId` will be assigned from the `moduleName` (which is specified in our case)

This is not a problem because we can just set `moduleId: ""` in the options, but I just wanted to make clear that I think it's better to not have any *magic* and rather let the developers decide.

**Comment by MikeKovarik** [comment]
Hello, first of all I apologize for delayed response, my senior year is super busy.

Thank you for using this plugin, I didn't expect it to be used much since it's absolute opposite of `gulp-rollup` which boasts about doing gulp & streams integration correctly (while stating `Note: This plugin is not appropriate for most use cases` as a first line of their readme). And as such I intentionaly made it more friendlier and easier to use. That goes for merging `rollupOptions` and `generateOptions` as well as auto assigning `moduleName` and `moduleId`.

You are right that this might not be the best way for everyone but it was preferable in most of my use cases and projects and I'd like to keep it easier to use out of the box so you can just drop into `.pipe(rollup('umd'))` into your pipeline and set other things if it's needed.

I however added the `moduleId: ''` trick into readme ;)
